### ISSUE TITLE
ComboBox seValueMethod throws java.lang.IllegalArgumentException: 

### ISSUE THREAD

**Issue by ajgarciac** [vaadin/vaadin-combo-box-flow#132]
When i call setValue in ComboBox, this throws java.lang.IllegalArgumentException

Caused by: java.lang.IllegalArgumentException: The provided value is not part of ComboBox: Colombia(COL)
	at com.vaadin.flow.component.combobox.ComboBox.setValue(ComboBox.java:526)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.initFieldValue(Binder.java:1119)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.access$200(Binder.java:966)
	at com.vaadin.flow.data.binder.Binder.lambda$readBean$2(Binder.java:1679)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.data.binder.Binder.readBean(Binder.java:1679)

Mi code is like this:

CityForm
`
public class CityForm extends FormLayout  implements KeyNotifier{

	private Binder<City> binder = new Binder<>(City.class);
	private ComboBox<Country> country = new ComboBox<>();
.
.
.
	public CityForm(CitiesView citiesView, CountryRepository countryRepository) {
	.
	.
	    country.setItems(countryRepository.findAll());;
		.
		.
	    binder.forField(country).bind(City::getCountry,City::setCountry);
	.
	.
	}

country.setItems(countryRepository.findAll());;
.
binder.forField(country).bind(City::getCountry,City::setCountry);
binder.bindInstanceFields(this);

`

City
`
@Entity
public class City {
.
.
	private Country country;
	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}
}
`

Thanks!

**Comment by eriklumme** [comment]
It's a good idea to override the `equals` method of the class that you show in the ComboBox, in this example `City`.

Otherwise you might, for example, get the same object from the database, but it will be a new Java instance. In this case, without overriding the equals method, there is no way for the ComboBox to know that `Colombia(COL)` that you're trying to set is the same `Colombia(COL)` that it has in its list.

**Comment by ajgarciac** [comment]
Thanks, i've made something like that,
All my database beans have a ID property, so, i have a class `DataBaseEntity` and all my database beans extend from this one. In this i override de `equals` method, in this, i compare the objects by the `getId()` result

```
public class DatabaseEntity {
	
	@Override
	public boolean equals(Object object) {
		
		if (object == null)
			return this == null;
		
		if (getId(object) == null)
			return getId() == null;
		
		if (object instanceof  DatabaseEntity) 
			return getId().equals(getId(object));
		else
			re.turn false;
	}
        .
        .
        .
}
```
Mi Country class is now this way:

```
@Entity
@Table(name="countries")
public class Country  extends DatabaseEntity{
        .
        .
        private Long id;
        .
        .
	public Long getId() {
		return id;
	}
        .
        .
        .
}
```

This worked for me!! Thanks for your reply
