### ISSUE TITLE
setItemLabelGenerator doesn't work when used after setValue

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/vaadin-combo-box-flow#170]
When I set the itemLabelGenerator after I set the value of a comboBox, the itemLabelGenerator does not work, instead the object's representation (`MyObject@41d8d522`) is shown. This worked in Vaadin 11.0.2 but not anymore in Vaadin 12.0.0

If I set the comboBox's value after setting the itemLabelGenerator, it works fine.

[Here](https://vaadin.com/forum/thread/17431429/17431430) is my Vaadin Forum post about it with more details and some code

**Comment by denis-anisimov** [comment]
I cannot reproduce this with the master branch at least.

Please **_always_** add a code snapshot which shows how to reproduce an issue.

It's very easy to use https://github.com/vaadin/skeleton-starter-flow project as a start and add your source code on the top of it.

I'm using this code: 
```
ComboBox<Object> combobox = new ComboBox<>();

        combobox.setItems(new Object(), new Object());
        combobox.setItemLabelGenerator(value -> UUID.randomUUID().toString());

        add(combobox);
```

items are rendered using random UUID regardless of the call order.

**Comment by KasparScherrer** [comment]
Oh in my haste I forgot to mention that it only happens inside of a ComponentRenderer of a Grid. It does not happen outside of a grid simply by adding a comboBox to a layout.  

Here is my code snippet for reproduction:

```
public class DashboardView extends VerticalLayout {

    public static final String VIEW_ROUTE = "Dashboard";

    public DashboardView(){
        VerticalLayout layout = new VerticalLayout();
        layout.add(new H2("ComboBox Label Issue"));


        Set<ComboBoxObject> options = new HashSet<>();
        options.add(new ComboBoxObject("Option 1"));
        options.add(new ComboBoxObject("Option 2"));
        options.add(new ComboBoxObject("Option 3"));
        options.add(new ComboBoxObject("Option 4"));

        Grid<GridObject> grid = new Grid<>();
        grid.addColumn(new ComponentRenderer<>(gridItem -> {
            ComboBox<ComboBoxObject> comboBox = new ComboBox<>();
            comboBox.setItems(options);
            comboBox.setValue(gridItem.getCbObject());
            comboBox.setItemLabelGenerator(ComboBoxObject::getName);
            return comboBox;
        }))
                .setHeader("buggy ComboBox")
                .setId("buggy");

        grid.addColumn(new ComponentRenderer<>(gridItem -> {
            ComboBox<ComboBoxObject> comboBox = new ComboBox<>();
            comboBox.setItemLabelGenerator(ComboBoxObject::getName);
            comboBox.setItems(options);
            comboBox.setValue(gridItem.getCbObject());
            return comboBox;
        }))
                .setHeader("working ComboBox")
                .setId("working");

        grid.setItems(new GridObject(), new GridObject(), new GridObject());

        layout.add(grid);
        add(layout);
    }

    public class ComboBoxObject {
        private String name = "Option 1";

        public ComboBoxObject(){
        }
        public ComboBoxObject(String name){
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

    public class GridObject {
        private ComboBoxObject cbObject;

        public GridObject(){
            this.cbObject = new ComboBoxObject();
        }

        public ComboBoxObject getCbObject() {
            return cbObject;
        }

        public void setCbObject(ComboBoxObject cbObject) {
            this.cbObject = cbObject;
        }
    }
}
```

When making the code snippet I first tried with java.utils.Locale as ComboBox class, but with Locale it worked with no problem. very confusing. Maybe it only doesn't work with relations between 2 classes (thats the case with my original code) so I made the 2 inline classes GridObject and ComboBoxObject and indeed the bug is happening again.

**Comment by denis-anisimov** [comment]
Java code from your sample throws an exception:

```
java.lang.IllegalArgumentException: The provided value is not part of ComboBox: com.vaadin.flow.component.grid.it.DashboardView$ComboBoxObject@1b0f317c
	at com.vaadin.flow.component.combobox.ComboBox.setValue(ComboBox.java:527)
	at com.vaadin.flow.component.grid.it.DashboardView.lambda$new$22ac751a$1(DashboardView.java:33)
	at com.vaadin.flow.data.renderer.ComponentRenderer.createComponent(ComponentRenderer.java:234)
	at com.vaadin.flow.data.provider.ComponentDataGenerator.createComponent(ComponentDataGenerator.java:90)
	at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:79)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47)
```

**Comment by denis-anisimov** [comment]
Now it works. Thanks.

As I understand I should see `Object.toString()` result in one case and meaningful rendering result in other case, right ?

If so then I cannot reproduce this with `Grid` snapshot.
In fact this issue may be not in the combobox, not in the grid . It might be a common Flow rendering issue and I'm using wrong version of Flow....

Please always use skeleton-starter project as as a starting point for the bug report.
Otherwise we are wasting time trying to understand which version you are referring to (you are creating a bug against the component _NOT a platform_ and I don't use platform for checking it because there is not project attached. As a result I can't understand where the bug is and in which component).
Attached project with the complete code allows to avoid any kind of misunderstanding.

**Comment by denis-anisimov** [comment]
Cannot reproduce it with `2.1-SNAPSHOT`.

**Comment by denis-anisimov** [comment]
Yep.
I can reproduce it with `12.0.2`  platform.
It has Grid `2.1.3`  and combobox `2.0.1` .
Flow version is `1.2.3`.

I'm pretty sure that the bug is inside `flow-data`  and not neither in `Grid` nor `ComboBox`.

But that's up to the developer.

**Comment by denis-anisimov** [comment]
Steps to reproduce:
- take https://github.com/vaadin/skeleton-starter-flow/tree/v12
- copy code from here and paste to the `MainView`  with proper changes.

Result is:
- the first grid shows incorrectly rendered items in its comboboxes.
- the second grid shows correctly rendered items in its comboboxes.
